I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 49, in script
    show daisyDefault easeinbottom zorder 2
Exception: Image 'daisyDefault' does not accept attributes 'easeinbottom'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 49, in script
    show daisyDefault easeinbottom zorder 2
  File "C:\Users\idaat\Desktop\renpy\renpy\ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\idaat\Desktop\renpy\renpy\ast.py", line 1391, in show_imspec
    renpy.config.show(name,
  File "C:\Users\idaat\Desktop\renpy\renpy\exports.py", line 733, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\idaat\Desktop\renpy\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\idaat\Desktop\renpy\renpy\display\transform.py", line 1043, in _duplicate
    args.extraneous()
  File "C:\Users\idaat\Desktop\renpy\renpy\display\core.py", line 283, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'daisyDefault' does not accept attributes 'easeinbottom'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.0.23051307
space yuri 1.0
Wed Jul 12 12:39:09 2023
